// Generated by CoffeeScript 1.6.3
(function() {
  var EditJsonMapAppViewModel,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  EditJsonMapAppViewModel = (function(_super) {
    __extends(EditJsonMapAppViewModel, _super);

    function EditJsonMapAppViewModel(initial) {
      var JsonMapsViewModel;
      JsonMapsViewModel = initial["JsonMapsViewModel"];
      delete initial.JsonMapsViewModel;
      EditJsonMapAppViewModel.__super__.constructor.call(this, initial);
      this.JsonMapsViewModel = new ko.ModelFactory.JsonMapsViewModel(this._stubs["JsonMapsViewModel"], JsonMapsViewModel, this.FormViewModel.TypeListViewModel.createAttributesListObservable, this.FormViewModel.ValidationMethodListViewModel.createArgumentsListObservable);
    }

    return EditJsonMapAppViewModel;

  })(ko.ModelFactory.AppViewModel);

  ko.ModelFactory.EditJsonMapAppViewModel = EditJsonMapAppViewModel;

}).call(this);

/*
//@ sourceMappingURL=EditJsonMapAppViewModel.map
*/
